# Find all the available rules by running:
# swiftlint rules
disabled_rules:
  - line_length #...
  - function_body_length #...
  - nesting #...
  - trailing_whitespace

analyzer_rules:
 - explicit_self
 - unused_import

opt_in_rules:
 - empty_count
 - private_outlet
 - static_operator
 - pattern_matching_keywords
 - vertical_parameter_alignment_on_call
 - multiline_parameters_brackets
 - collection_alignment
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - unneeded_parentheses_in_closure_argument
 - operator_usage_whitespace
 - anyobject_protocol
 - prohibited_super_call
 - closure_spacing
 - contains_over_first_not_nil
 - convenience_type
 - empty_string
 - fallthrough
 - first_where
 - literal_expression_end_indentation
 - overridden_super_call
 - override_in_extension
 - sorted_imports
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces

excluded:
 -  Carthage
large_tuple: 3 
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - up
    - i
    - to
reporter: "xcode"
