name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: | 
          pwd
          ls -al
          bundle install

      - name: Install Carthage
        run: bundle exec fastlane kit_carthage_build