name: Unit Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_11.2.app/Contents/Developer']
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: | 
          pwd
          ls -al
          bundle install

      - name: Install Carthage
        run: bundle exec fastlane kit_carthage_build
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}