name: Unit Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.2]
    steps:
      - uses: actions/checkout@v1
      
      - name: Install dependencies
        run: bundle install

      - name: Select XCode
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'

      - name: Install Carthage
        run: bundle exec fastlane kit_carthage_build

      - name: Run Unit Tests
        run: bundle exec fastlane kit_test