name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Install dependencies
        run: bundle exec fastlane kit_carthage_build